### ISSUE TITLE
Unexpected Performance Differences

### ISSUE THREAD

**Issue by FreuMi** [SDM-TIB/SDM-RDFizer#118]
**Unexpected Performance Differences**

I am experiencing a significant performance difference when using different versions of RDFizer to map the [GTFS-madrid-bench](https://github.com/oeg-upm/gtfs-bench). I measured execution time and peak memory usage with `/usr/bin/time -v`.

When using the latest version of RDFizer (`4.7.4.12`), the mapping of GTFS-madrid-bench scale 1 takes about 238 seconds and consumes 190 MB of memory. 
In contrast, using an older version of RDFizer (`4.7.2.4`) with the same config file and on the same machine, the mapping takes only about 11 seconds and uses 176 MB of memory, which seems more reasonable. The RDF output of both versions is identical.

Could you clarify if this change in performance is expected? Are there any adjustments I can make to the configuration or setup to achieve similar performance with the newer version? Any guidance would be greatly appreciated.

**config file**
```
[default]
main_directory: .

[datasets]
number_of_datasets: 1
output_folder: output
remove_duplicate: yes
all_in_one_file: no
name: rdfizer_output
enrichment: yes
ordered: yes
output_format: n-triples

[dataset1]
name: rdfizer_output
mapping: ./gtfs/scale_1/mapping.ttl
```

**Desktop**
 - OS: Ubuntu 24.04
- 64 GB RAM
- 8 cores @ 2GHz

**Comment by eiglesias34** [comment]
Hello @FreuMi,

I hope you are doing well. Thank you for noticing this issue. What happened was that I saw during the test cases for the KGCW challenge this year that the criteria for converting a self-join where the join condition of the parent and child are the same was not as strict as it should be and in some cases, not all the triples were not being generated. So, I removed it until I improved the criteria. I have been working on this recently but have yet to apply it to the SDM-RDFizer. I made a new release with the new criteria, and I tested it out, and it went from taking 233.33 sec to 7.07. Please test it out on your side, and I hope your problem is solved.

Sincerely,
Enrique Iglesias

**Comment by FreuMi** [comment]
Hi @eiglesias34,

Thanks for the quick fix. Performance is now as expected.

Best,
Michael Freund
