### ISSUE TITLE
Unable to get the Output folder

### ISSUE THREAD

**Issue by Gautamshahi** [SDM-TIB/SDM-RDFizer#28]
Hello,

I have followed the instructions given in the video. I am not able to get the output folder. Everything is running fine. Can you please help me to rectify the issue?

![image](https://user-images.githubusercontent.com/3966230/88468013-075fc580-cede-11ea-981e-eb5453398b9a.png)

**Comment by mevs** [comment]
Many thanks for contacting us.

Since the output wasn't generated automatically this could mean that one of the following could have happened:
- The files weren't properly uploaded to the docker container. To check this please run docker logs CONTAINER_ID. If the log says that your files don't exist, that means the files weren't properly uploaded. As a simpler way to upload the files, you can copy the files to the example folder in the root directory of the SDM-RDFier and upload the data from there. Please note that configuration and mapping files must reflect the fact that they're in the container. Also, when uploading the data, please use the complete path to the data.
- The other case is that you might have to download the output folder from the container by executing this command 
docker cp CONTAINER_ID:/app/path/to/output.

As an alternative, you can run the SDM-RDFizer directly from the terminal by using Python.
pip3 install -r requeriments.txt
python3 rdfizer/run_rdfizer.py /path/to/config/FILE
In this case, the mapping and configuration files must reflect the fact that you're executing the SDM-RDFizer locally, meaning the path must indicate the location of the files within your file system.

Thank you again.

**Comment by Gautamshahi** [comment]
Hello,

Thank you very much for the brief reply, I tried both options but it didn't work. I am also attaching the details about the container. Please let me know where I am doing wrong, I exactly followed the run instructions on https://github.com/SDM-TIB/SDM-RDFizer-Experiments/blob/master/cikm2020/motivating-example/README.md

container id
![image](https://user-images.githubusercontent.com/3966230/88481103-d2915400-cf59-11ea-9700-7e19fcb386a8.png)

container log
![image](https://user-images.githubusercontent.com/3966230/88481043-a970c380-cf59-11ea-8afb-b293198d6932.png)

Trying to copy the output file
![image](https://user-images.githubusercontent.com/3966230/88481131-f2287c80-cf59-11ea-8bac-491643a5fac9.png)\

Apart from executing the experiment, I am also wondering how the RDFizer is reading the ontology file in the mapping file(like prefix @prefix iasis: <http://project-iasis.eu/vocab/> .)? Do we need to save our ontology somewhere?

It will be really helpful if I can get any full documentation about the tool. I also watched your video( https://www.youtube.com/watch?v=DpH_57M1uOE) but the folder structure is also different from the GitHub repository.

I will be thankful if you help me to resolve the issue.

**Comment by eiglesias34** [comment]
First, the "KeyError" indicates that there is a problem with the configuration file. Please make sure that the configuration file follows the examples given in the wiki. Second, you're executing the copy of the output folder incorrectly. "/path/to/output" means the path to the output folder in the container. Also, since there was a problem with the execution with the SDM-RDFizer there is no output folder.
